version: '3.8'

services:
  server1:
    build: .
    networks:
      my_lan_network:
        ipv4_address: 192.168.1.102

  server2:
    build: .
    networks:
      my_lan_network:
        ipv4_address: 192.168.1.101

  server3:
    build: .
    networks:
      my_lan_network:
        ipv4_address: 192.168.1.100

networks:
  my_lan_network:
    external: true

